name: Test package

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build
        working-directory: ./package

      - name: Test package general
        run: |
          pnpm install next@canary
          pnpm playwright install
          pnpm build
          pnpm test
        working-directory: ./tests/base

      - name: Set summary
        run: |
          NEXT_VERSION=$(node -p "require('next/package.json').version")
          echo "$NEXT_VERSION" >> $GITHUB_STEP_SUMMARY
        working-directory: ./tests/base
